# ********RoostGPT********

# Test generated by RoostGPT for test karate-claude using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /deposit_post for http method type POST 
# RoostTestHash=70db6d5eac
# 
# 

# ********RoostGPT********
Feature: Test /deposit API endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def reqBody = read('classpath:request-bodies/deposit-req-body.json')

  Scenario: Successful deposit
    Given path '/deposit'
    And header koreUserId = 'user123'
    And header botId = 'bot456'  
    And header accountId = 'acc789'
    And header Authorization = AUTH_TOKEN
    And request reqBody
    When method POST
    Then status 200
    And match response == {}

  Scenario: Unauthorized request
    Given path '/deposit'
    And header koreUserId = 'user123'
    And header botId = 'bot456'
    And header accountId = 'acc789'  
    And header Authorization = 'invalidToken'
    And request reqBody
    When method POST 
    Then status 401
    And match response.err.message == 'Error: Authorisation failed.'

  Scenario: Resource not found
    Given path '/deposit'
    And header koreUserId = 'user123'
    And header botId = 'invalidBotId'
    And header accountId = 'acc789'
    And header Authorization = AUTH_TOKEN
    And request reqBody  
    When method POST
    Then status 404
    And match response.err.message == 'Error: Not Found'
