# ********RoostGPT********

# Test generated by RoostGPT for test karate-claude using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=36bc161fb6
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  #* configure headers = { 'Authorization': 'Bearer ' + karate.properties['AUTH_TOKEN'] }
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Get employee by ID
  Given url urlBase
  And header Authorization = authToken
  And path '/employees/d290f1ee-6c54-4b01-90e6-d701748f0851'
  When method GET
  Then status 200
  And match response ==
    """
    {
      id: 'd290f1ee-6c54-4b01-90e6-d701748f0851',
      jobTitle: 'System Analyst',
      name: 'John Smith',
      email: 'john.smith@acme-corp.com'
    }
    """

Scenario: Verify employee details
  Given url urlBase
  And header Authorization = authToken
  And path '/employees/d290f1ee-6c54-4b01-90e6-d701748f0851'
  When method GET
  Then status 200
  And match response.id == 'd290f1ee-6c54-4b01-90e6-d701748f0851'
  And match response.jobTitle == 'System Analyst'
  And match response.name == 'John Smith'
  And match response.email == 'john.smith@acme-corp.com'

Scenario: Get non-existent employee
  Given url urlBase
  And header Authorization = authToken
  And path '/employees/non-existent-id'
  When method GET
  Then status 404

Scenario Outline: Get employee by ID with examples
  Given url urlBase
  And header Authorization = authToken
  And path '/employees/<id>'
  When method GET
  Then status <status>
  And match response == <response>

  Examples:
    | id                                   | status | response                                                                                                                         |
    | d290f1ee-6c54-4b01-90e6-d701748f0851 | 200    | """{ id: 'd290f1ee-6c54-4b01-90e6-d701748f0851', jobTitle: 'System Analyst', name: 'John Smith', email: 'john.smith@acme-corp.com' }""" |
    | non-existent-id                      | 404    | null                                                                                                                             |
