# ********RoostGPT********

# Test generated by RoostGPT for test karate-claude using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Search employees with valid search string
    Given path '/employees'
    And param searchString = 'John'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response == '#[_ > 0]'
    And match each response contains
        """
        {
            email: '#string',
            jobTitle: '#string',
            name: '#string'
        }
        """
    And match response[0].id == '#uuid'
    And match response[0].email contains 'acme-corp.com'
    And match response[0].jobTitle == 'System Analyst'
    And match response[0].name == 'John Smith'

Scenario: Search employees without search string
    Given path '/employees'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response == '#[_ > 0]'
    And match each response contains
        """
        {
            email: '#string',
            jobTitle: '#string',
            name: '#string'
        }
        """

Scenario: Search employees with invalid search string
    Given path '/employees'
    And param searchString = 'InvalidSearchString'
    And header Authorization = authToken
    When method GET
    Then status 200
    And match response == '#[0]'

Scenario: Search employees with invalid authorization token
    Given path '/employees'
    And param searchString = 'John'
    And header Authorization = 'InvalidAuthToken'
    When method GET
    Then status 401

Scenario: Search employees with missing authorization token
    Given path '/employees'
    And param searchString = 'John'
    When method GET
    Then status 401
