# ********RoostGPT********

# Test generated by RoostGPT for test karate-claude using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=b517afeac4
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario: Add a new employee
  Given path '/employees'
  And request
    """
    {
      "jobTitle": "System Analyst",
      "name": "John Smith",
      "email": "john.smith@acme-corp.com"
    }
    """
  And header Authorization = authToken
  When method POST
  Then status 201

Scenario: Add a new employee with generated UUID
  Given path '/employees'
  And def uuid = java.util.UUID.randomUUID() + ''
  And request
    """
    {
      "id": "#(uuid)",
      "jobTitle": "Software Engineer", 
      "name": "Jane Doe",
      "email": "jane.doe@acme-corp.com"
    }
    """
  And header Authorization = authToken
  When method POST
  Then status 201

Scenario: Add an employee with missing required fields
  Given path '/employees'
  And request
    """
    {
      "jobTitle": "Product Manager"
    }
    """
  And header Authorization = authToken
  When method POST
  Then status 400

Scenario: Add a duplicate employee
  Given path '/employees'
  And request
    """
    {
      "jobTitle": "System Analyst",
      "name": "John Smith",
      "email": "john.smith@acme-corp.com"
    }
    """
  And header Authorization = authToken
  When method POST
  Then status 409
