
// ********RoostGPT********
/*

# Test generated by RoostGPT for test ProductOrde-Karate-productOrder-api using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=0e2f009f7e
# 
# 

roost_feedback [6/3/2024, 11:24:18 AM]:Add comments in tests scenarios
*/

// ********RoostGPT********


# Test generated by RoostGPT for test ProductOrde-Karate-productOrder-api using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=0e2f009f7e
# 
# 

Feature: Search Time Slot API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Retrieve Search Time Slot - Successful Response
    # Test case to verify successful retrieval of search time slots
    Given path '/searchTimeSlot'
    And param addressId = <addressId>
    And param subscriberId = <subscriberId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param addressChangeFlag = <addressChangeFlag>
    And param productType = <productType>
    And param priorityFlag = <priorityFlag>
    And param priorityReason = <priorityReason>
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 200
    And match response.control.type == 'S'
    And match response.control.code == 200
    And match response.control.message == 'OK'
    And match response.slots == '#array'
    And match each response.slots contains { id: '#string', startDate: '#string', finishDate: '#string', expireIn: '#number' }

    Examples:
      | read('searchTimeSlot_get.csv') |

  Scenario: Retrieve Search Time Slot - Bad Request
    # Test case to verify handling of bad request
    Given path '/searchTimeSlot'
    And param addressId = 'invalid'
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 400
    And match response.control.type == 'E'
    And match response.control.code == 400
    And match response.control.message == 'Bad Request'

  Scenario: Retrieve Search Time Slot - Unauthorized
    # Test case to verify handling of unauthorized access
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    When method GET
    Then status 401
    And match response.control.type == 'E'
    And match response.control.code == 401
    And match response.control.message == 'Unauthorized'

  Scenario: Retrieve Search Time Slot - Forbidden - Scope Not Permitted
    # Test case to verify handling of forbidden access due to scope not permitted
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer invalidToken'
    When method GET
    Then status 403
    And match response.control.type == 'E'
    And match response.control.code == 403
    And match response.control.message == 'Forbidden - Scope Not Permitted'

  Scenario: Retrieve Search Time Slot - Not Found
    # Test case to verify handling of resource not found
    Given path '/searchTimeSlot'
    And param addressId = 99999
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 404
    And match response.control.type == 'E'
    And match response.control.code == 404
    And match response.control.message == 'Not Found'

  Scenario: Retrieve Search Time Slot - Not Acceptable
    # Test case to verify handling of not acceptable request
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'InvalidType'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 406
    And match response.control.type == 'E'
    And match response.control.code == 406
    And match response.control.message == 'Not Acceptable'

  Scenario: Retrieve Search Time Slot - Precondition Failed
    # Test case to verify handling of precondition failed
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-05-20T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 412
    And match response.control.type == 'E'
    And match response.control.code == 412
    And match response.control.message == 'Precondition Failed'

  Scenario: Retrieve Search Time Slot - Too Many Requests - Exceeded Quota
    # Test case to verify handling of too many requests and exceeded quota
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 429
    And match response.control.type == 'E'
    And match response.control.code == 429
    And match response.control.message == 'Too Many Requests - Exceeded Quota'

  Scenario: Retrieve Search Time Slot - Internal Server Error
    # Test case to verify handling of internal server error
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 500
    And match response.control.type == 'T'
    And match response.control.code == 500
    And match response.control.message == 'Internal Server Error'

  Scenario: Retrieve Search Time Slot - Service Unavailable
    # Test case to verify handling of service unavailability
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 503
    And match response.control.type == 'T'
    And match response.control.code == 503
    And match response.control.message == 'Service Unavailable'

  Scenario: Retrieve Search Time Slot - Gateway Timeout
    # Test case to verify handling of gateway timeout
    Given path '/searchTimeSlot'
    And param addressId = 17713
    And param associatedDocument = 'VTT001'
    And param startDate = '2021-05-21T13:00:00'
    And param finishDate = '2021-06-04T13:00:00'
    And param orderType = 'Instalacao'
    And param productType = 'Banda Larga'
    And header Authorization = 'Bearer ' + authToken
    When method GET
    Then status 504
    And match response.control.type == 'T'
    And match response.control.code == 504
    And match response.control.message == 'Gateway Timeout'
