# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-credential using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /accounts_patch for http method type PATCH 
# RoostTestHash=2758affb7e
# 
# 

# ********RoostGPT********
Feature: Login to existing Account

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario: Successful login with valid email
  Given path '/accounts'
  And request { "email": "test@example.com" }
  When method POST
  Then status 200
  And match header api-version == '1.0.0'

Scenario: Login with invalid email format
  Given path '/accounts'
  And request { "email": "invalid_email" }
  When method POST
  Then status 400
  And match header api-version == '1.0.0'
  And match response.error contains 'validation/email-pattern'
  And match response.description == 'Descriptive Error Message'
  And match response.field == 'email'
  And match response.schema_field == '#present'

Scenario: Login with missing email field
  Given path '/accounts'
  And request { }
  When method POST
  Then status 400
  And match header api-version == '1.0.0'
  And match response.error == 'error/code'
  And match response.description == 'Descriptive Error Message'
