# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees_post for http method type POST 
# RoostTestHash=b517afeac4
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(authToken)' }

Scenario: Add a new employee
    Given path '/employees'
    And request
        """
        {
            "jobTitle": "System Analyst",
            "name": "John Smith",
            "email": "john.smith@acme-corp.com"
        }
        """
    When method POST
    Then status 201

Scenario: Add a new employee with UUID
    Given path '/employees'
    And request
        """
        {
            "id": "d290f1ee-6c54-4b01-90e6-d701748f0851",
            "jobTitle": "System Analyst",
            "name": "John Smith",
            "email": "john.smith@acme-corp.com"
        }
        """
    When method POST
    Then status 201

Scenario: Add a new employee with missing required fields
    Given path '/employees'
    And request
        """
        {
            "jobTitle": "System Analyst"
        }
        """
    When method POST
    Then status 400

Scenario: Add a duplicate employee
    Given path '/employees'
    And request
        """
        {
            "jobTitle": "System Analyst",
            "name": "John Smith",
            "email": "john.smith@acme-corp.com"
        }
        """
    When method POST
    Then status 409
