# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees_get for http method type GET 
# RoostTestHash=ec231a756b
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(authToken)' }

Scenario: Search employees with valid search string
    Given path '/employees'
    And param searchString = 'John'
    When method GET
    Then status 200
    And match response == '#[_ > 0]'
    And match each response contains
        """
        {
            email: '#string',
            jobTitle: '#string',
            name: '#string'
        }
        """
    And match each response contains { id: '#uuid' }

Scenario: Search employees without search string
    Given path '/employees'
    When method GET
    Then status 200
    And match response == '#[_ > 0]'
    And match each response contains
        """
        {
            email: '#string',
            jobTitle: '#string',
            name: '#string'
        }
        """
    And match each response contains { id: '#uuid' }

Scenario: Search employees with invalid search string
    Given path '/employees'
    And param searchString = 'InvalidSearchString'
    When method GET
    Then status 200
    And match response == '#[0]'

Scenario: Search employees with bad input
    Given path '/employees'
    And param searchString = '123'
    When method GET
    Then status 400
