# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=36bc161fb6
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Get employee by ID
  Given path '/employees/<id>'
  And header Authorization = authToken
  When method GET
  Then status 200
  And match response == 
  """
  {
    id: '#string',
    jobTitle: '#string',
    name: '#string',
    email: '#string'
  }
  """
  And match response.id == '<id>'
  And match response.jobTitle == '<jobTitle>'
  And match response.name == '<name>'
  And match response.email == '<email>'

  Examples:
    | id                                   | jobTitle      | name       | email                     |
    | d290f1ee-6c54-4b01-90e6-d701748f0851 | System Analyst | John Smith | john.smith@acme-corp.com |

Scenario: Get non-existent employee
  Given path '/employees/invalid-id' 
  And header Authorization = authToken
  When method GET
  Then status 404
