# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /employees/{id}_get for http method type GET 
# RoostTestHash=36bc161fb6
# 
# 

# ********RoostGPT********
Feature: Employee API

Background:
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * def id = 'd290f1ee-6c54-4b01-90e6-d701748f0851'
  * configure headers = { 'Authorization': '#' + AUTH_TOKEN }
  * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
  * url urlBase

Scenario Outline: Gets employee by ID
    Given path '/employees/', '<id>'
    And method get
    When header Authorization = '#'+AUTH_TOKEN
    Then status 200
    And match response contains { email: '#string', jobTitle: '#string', name: '#string' }
    And match responseTypes == { id: '#uuid', email : '#string', jobTitle: '#string', name: '#string'}
    And match responseHeaders.contains { 'Content-Type': 'application/json' }

Examples:
| id                                |
| 'd290f1ee-6c54-4b01-90e6-d701748f0851' |

Scenario Outline: Employee not found
    Given path '/employees/', '<id>'
    And method get
    Then status 404

Examples:
| id      |
| '12345' |
