# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-credential using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /login_post for http method type POST 
# RoostTestHash=3122292ee3
# 
# 

# ********RoostGPT********
Feature: Login API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * configure headers = { 'Token': '#(AUTH_TOKEN)' }

Scenario Outline: Login using OTP - Successful
  Given path '/login'
  And request { "email": "<email>", "otp": "<otp>", "client": "<client>" }
  When method POST
  Then status 201
  And match header api-version == '1.0.0'
  And match response.token == '#regex ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

  Examples:
    | email              | otp    | client  |
    | user1@example.com  | 123456 | mobile  |
    | user2@example.com  | 654321 | web     |
    | user3@example.com  | 111111 | desktop |
    | user4@example.com  | 999999 | api     |

Scenario Outline: Login using OTP - Bad Request (Invalid email format)
  Given path '/login' 
  And request { "email": "<email>", "otp": "<otp>", "client": "<client>" }
  When method POST
  Then status 400
  And match header api-version == '1.0.0'
  And match response.error == 'validation/email-pattern'
  And match response.description == 'Descriptive Error Message'
  And match response.field == 'email'

  Examples:
    | email         | otp    | client |
    | invalid.email | 123456 | mobile |
    | abc@          | 654321 | web    |

Scenario Outline: Login using OTP - Bad Request (Missing required fields)
  Given path '/login'
  And request <payload>
  When method POST
  Then status 400 
  And match header api-version == '1.0.0'
  And match response.error == 'error/code'
  And match response.description == 'Descriptive Error Message'

  Examples:
    | payload                                |
    | { "email": "user@example.com" }        |
    | { "otp": "123456" }                    | 
    | { "client": "mobile" }                 |
    | { "email": "user@example.com", "otp": "123456" }  |
