# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-credential using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /logout_post for http method type POST 
# RoostTestHash=64d33906e5
# 
# 

# ********RoostGPT********
Feature: Logout API

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
* url urlBase
* configure headers = { 'Token': '#(karate.properties.AUTH_TOKEN)' }

Scenario: Successful logout
    Given path '/logout'
    When method delete
    Then status 200
    And match header api-version == '1.0.0'

Scenario: Bad Request - Invalid token
    Given path '/logout' 
    And header Token = 'invalid_token'
    When method delete
    Then status 400
    And match header api-version == '1.0.0'
    And match response.error == 'error/code'
    And match response.description == 'Descriptive Error Message'

Scenario: Bad Request - Validation error
    Given path '/logout'
    And header Token = '#(karate.properties.AUTH_TOKEN)'
    When method delete
    Then status 400 
    And match header api-version == '1.0.0'
    And match response.error == '#regex ^validation/.*$'
    And match response.description == 'Descriptive Error Message'
    And match response.schema_field == '#string'
    And match response.field == '#string'
