# ********RoostGPT********

# Test generated by RoostGPT for test karate-test-credential using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /me_get for http method type GET 
# RoostTestHash=ae6b8ce5ab
# 
# 

# ********RoostGPT********
Feature: Account API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
  * headers { Token: '#(AUTH_TOKEN)' }

Scenario: Get my account details successfully
  Given path '/me'
  When method GET
  Then status 200
  And match header api-version == '1.0.0'
  And match response == 
    """
    {
      id: '#uuid',
      did: '##string',
      name: '#string? pattern("^[\\p{L} .'-]{1,100}$")',
      image: '#string? pattern("^\\w+:(\\/?\\/?)[^\\s]+$")',
      email: '#email',
      settings: '#object',
      createdAt: '#datetime',
      updatedAt: '#datetime'
    }
    """

Scenario: Get my account details with missing authentication token
  Given path '/me'
  And headers { Token: '' }
  When method GET
  Then status 401
  And match header api-version == '1.0.0'
  And match response ==
    """
    {
      error: '#string',
      description: '#string'
    }
    """

Scenario: Get my account details with invalid email format
  Given path '/me'
  When method GET
  Then status 400
  And match header api-version == '1.0.0'
  And match response ==
    """
    {
      error: '#regex ^validation/.*$',
      description: '#string',
      value: '#present',
      field: '#string',
      schema_field: '#string'
    }
    """
